"""
Dummy call simulation — no browser, no phone required.

Prospect lines are pre-scripted and printed to the terminal.
Tony's replies are generated by the real Groq LLM and (by default) spoken
aloud through your default system speakers via edge-tts.

Usage:
    python -m src.simulate_call               # TTS audio + printed text
    python -m src.simulate_call --text-only   # printed text only (no audio)
    python -m src.simulate_call --device N    # play to sounddevice output #N
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# ── Prospect script ──────────────────────────────────────────────────────────
# Each entry is what the simulated prospect says.  Covers the most common
# objections and one positive close so the full conversation arc is exercised.

PROSPECT_LINES = [
    "Hello?",
    "Who is this?",
    "How did you get my number?",
    "I already have a dispatcher, I'm good.",
    "What do you guys charge?",
    "Can you guarantee I'll make at least five grand a week?",
    "Okay, look, I'm actually between dispatchers right now. What's the next step?",
    "Sure, Thursday afternoon works. What time?",
]


# ── ANSI colour helpers ──────────────────────────────────────────────────────

_RESET   = "\033[0m"
_BOLD    = "\033[1m"
_CYAN    = "\033[36m"
_YELLOW  = "\033[33m"
_GREEN   = "\033[32m"
_DIM     = "\033[2m"


def _print_prospect(text: str) -> None:
    print(f"\n{_CYAN}{_BOLD}[PROSPECT]{_RESET} {_CYAN}{text}{_RESET}")


def _print_tony(text: str) -> None:
    print(f"{_YELLOW}{_BOLD}[TONY    ]{_RESET} {_YELLOW}{text}{_RESET}")


def _print_info(text: str) -> None:
    print(f"{_DIM}  {text}{_RESET}")


# ── Core simulation ──────────────────────────────────────────────────────────

def run_simulation(text_only: bool = False, device_index: int | None = None) -> None:
    from src.config import Config
    from src.conversation_agent import ConversationAgent

    # Load configuration (.env must exist)
    try:
        cfg = Config.load()
        cfg.validate()
    except SystemExit as exc:
        print(f"Config error: {exc}")
        sys.exit(1)

    # Transcript destination
    ts_str = time.strftime("%Y%m%d_%H%M%S")
    transcript_path = BASE_DIR / "logs" / "transcripts" / f"simulate_{ts_str}.txt"
    transcript_path.parent.mkdir(parents=True, exist_ok=True)

    _write = lambda speaker, text: transcript_path.open("a", encoding="utf-8").write(
        f"[{time.strftime('%H:%M:%S')}] {speaker}: {text}\n"
    )

    # TTS setup
    tts = None
    if not text_only:
        tts = _setup_tts(cfg, device_index)
        if tts is None:
            print(f"{_DIM}TTS unavailable — falling back to text-only mode.{_RESET}")
            text_only = True

    # Agent setup
    agent = ConversationAgent(
        api_key=cfg.groq_api_key,
        model=cfg.groq_model,
        agent_name=cfg.agent_name,
        company_name=cfg.company_name,
        company_context=cfg.company_context,
        company_website=cfg.company_website,
        callback_number=cfg.callback_number,
        contact_name="Demo Carrier",
    )

    print("\n" + "=" * 60)
    print("  INDUS TRANSPORTS LLC — Call Simulation")
    print(f"  Agent: {cfg.agent_name}  |  Company: {cfg.company_name}")
    mode = "text-only" if text_only else "TTS audio"
    print(f"  Mode: {mode}  |  Transcript: {transcript_path.name}")
    print("=" * 60 + "\n")

    # Opening line
    opening = agent.opening_line()
    if opening:
        _print_info("(call connects — Tony speaks first)")
        _print_tony(opening)
        _write("Tony", opening)
        if tts:
            tts.speak(opening)
        time.sleep(0.4)

    # Conversation turns
    for prospect_text in PROSPECT_LINES:
        time.sleep(0.6)
        _print_prospect(prospect_text)
        _write("Prospect", prospect_text)
        time.sleep(0.3)

        _print_info("(Tony thinking…)")
        response = agent.respond_to(prospect_text)
        if not response:
            response = "Let me follow up on that."

        _print_tony(response)
        _write("Tony", response)
        if tts:
            tts.speak(response)

        if agent.should_end_call():
            _print_info("(agent signalled end of call)")
            goodbye = agent.goodbye_line()
            if goodbye:
                _print_tony(goodbye)
                _write("Tony", goodbye)
                if tts:
                    tts.speak(goodbye)
            break

    print("\n" + "=" * 60)
    print(f"  Simulation complete. Transcript saved:")
    print(f"  {transcript_path}")
    print("=" * 60 + "\n")


def _setup_tts(cfg, device_index: int | None):
    """Build a RealtimeTTS pointed at the default output device (or device_index)."""
    try:
        import sounddevice as sd
        from src.realtime_tts import RealtimeTTS

        if device_index is None:
            # sd.query_devices returns the default output device as a dict
            default_info = sd.query_devices(kind="output")
            device_index = int(default_info["index"])

        voice = getattr(cfg, "tts_voice", "en-US-GuyNeural") or "en-US-GuyNeural"
        return RealtimeTTS(device_index=device_index, voice=voice)
    except Exception as exc:
        print(f"TTS setup error: {exc}")
        return None


# ── Entry point ───────────────────────────────────────────────────────────────

def _parse() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Simulate a dispatch outreach call")
    p.add_argument("--text-only", action="store_true",
                   help="Print conversation only — no TTS audio")
    p.add_argument("--device", type=int, default=None, metavar="N",
                   help="sounddevice output device index for TTS (default: system default)")
    return p.parse_args()


if __name__ == "__main__":
    args = _parse()
    run_simulation(text_only=args.text_only, device_index=args.device)
